const RUNTIME_MANIFEST = require('../src/runtime-manifest.json');

const FRONTEND_SOURCES = [
  'src/app-loader.js',
  'src/app-core-01.js',
  'src/app-core-02.js',
  'src/app-core-03.js',
  'src/app-core-04.js',
  'src/app-core-05.js',
  'src/app-core-06.js',
  'src/cafe24-api.js',
  'src/cafe24-fields.js',
  'src/cafe24-options.js',
  'src/cafe24-product-form.js',
  'src/cafe24-payloads.js',
  'src/cafe24-sync.js',
];

const BACKEND_SOURCES = [
  'backend/app.py',
  'backend/routes/api.py',
  'backend/routes/api_core.py',
  'backend/routes/api_archive.py',
  'backend/routes/api_marketplus.py',
  'backend/routes/api_shared.py',
  'backend/routes/api_vm.py',
  'backend/routes/api_workspace_lock.py',
  'backend/services/workspace_lock_store.py',
  'backend/services/workspace_lock_service.py',
];

const RUNTIME_SOURCES = [...new Set([
  'app.html',
  'src/runtime-manifest.json',
  RUNTIME_MANIFEST.loader,
  RUNTIME_MANIFEST.authorityModule,
  ...(RUNTIME_MANIFEST.modules || []),
  ...(RUNTIME_MANIFEST.scripts || []),
  RUNTIME_MANIFEST.bundle,
  ...BACKEND_SOURCES,
  'tools/build_runtime_bundle.cjs',
  'tools/factory_cdp_test_utils.cjs',
  'tools/regression_manifest.cjs',
  'tools/run_daily_regression.cjs',
  'tools/runtime_source_guard.cjs',
  'tools/verify_handoff_gate.cjs',
  'tools/verify_oauth_status_workspace_isolation_v246.cjs',
  'tools/verify_three_session_workspace_revision_v230.cjs',
  'tools/verify_workspace_conflict_cdp_v233.cjs',
  'tools/measure_factory_perf_cdp_v79.cjs',
  'tools/verify_factory_new_file_blank_cdp_v85.cjs',
  'tools/verify_factory_size_preview_confirm_cdp_v545.cjs',
].filter(Boolean))];

const MANUAL_EXTERNAL_GATES = [
  'Vertex 실제 이미지 생성 1장씩: 비용과 quota를 사용하므로 수동 승인 후 실행',
  'VM 오픈마켓 5곳 실제 수집: VM/로그인/마켓 상태가 필요한 별도 실환경 검사',
  'Cafe24 실제 상품 등록: 새 상품·진열안함·판매안함·오픈마켓 안 함으로 마지막에만 실행',
  'GPT/Google/Cafe24 OAuth 재로그인: 저장된 인증 만료 시에만 API Hub 상태 확인 후 실행',
];

const MODULE_TARGET_GATES = Object.freeze([
  ['MENU-UPLOAD', '업로드 메뉴'],
  ['MENU-ANALYSIS', '분석 메뉴'],
  ['MENU-COMP', '경쟁사 메뉴'],
  ['MENU-SECTIONS', '섹션 메뉴'],
  ['MENU-GENERATE', '상세 생성 메뉴'],
  ['MENU-PREVIEW', '미리보기 메뉴'],
  ['MENU-CUTS', '이미지컷 메뉴'],
  ['MENU-OPTIONS', '옵션분류기 메뉴'],
  ['MENU-FACTORY', '조립공장 메뉴'],
  ['MENU-AUTO', '자동화 메뉴'],
  ['MENU-SETTINGS', '모델 설정 메뉴'],
  ['MENU-REPORTS', '작업 리포트 메뉴'],
  ['MENU-MANUAL', '사용설명서 메뉴'],
  ['FACTORY-START', '조립공장 시작 탭'],
  ['FACTORY-DB', '조립공장 DB 탭'],
  ['FACTORY-FIELDS', '조립공장 필수값 탭'],
  ['FACTORY-COMP', '조립공장 경쟁사 탭'],
  ['FACTORY-ASSETS', '조립공장 이미지 탭'],
  ['FACTORY-SECTIONS', '조립공장 상세페이지 탭'],
  ['FACTORY-PUBLISH', '조립공장 등록 탭'],
].map(([id, title]) => Object.freeze({ id, title })));

function nodeFile(id, area, title, file, tier = 'daily', timeoutMs = 360000) {
  return { id, area, title, tier, command: process.execPath, args: [file], timeoutMs };
}

function nodeTestPattern(id, area, title, file, pattern, tier = 'fast', timeoutMs = 120000) {
  return {
    id,
    area,
    title,
    tier,
    command: process.execPath,
    args: ['--test', '--test-name-pattern', pattern, file],
    timeoutMs,
  };
}

function buildRegressionSteps(pythonExe) {
  const syntaxSteps = FRONTEND_SOURCES.map((file, index) => ({
    id: `SYN-JS-${String(index + 1).padStart(2, '0')}`,
    area: '공통/문법',
    title: `${file} 문법 검사`,
    tier: 'fast',
    command: process.execPath,
    args: ['--check', file],
    timeoutMs: 60000,
  }));
  return [
    ...syntaxSteps,
    {
      id: 'SYN-MJS-01', area: '공통/문법', title: 'workspace revision 모듈 문법 검사', tier: 'fast',
      command: process.execPath, args: ['--check', 'src/modules/workspace-revision.mjs'], timeoutMs: 60000,
    },
    {
      id: 'SYN-MJS-02', area: '공통/문법', title: 'workspace authority 모듈 문법 검사', tier: 'fast',
      command: process.execPath, args: ['--check', 'src/modules/workspace-lock.mjs'], timeoutMs: 60000,
    },
    {
      id: 'SYN-MJS-03', area: '공통/문법', title: 'workspace authority 프로토콜 문법 검사', tier: 'fast',
      command: process.execPath, args: ['--check', 'src/modules/workspace-lock-protocol.mjs'], timeoutMs: 60000,
    },
    {
      id: 'BUILD-01', area: '공통/실행 기준', title: 'runtime bundle과 manifest/source 일치 검사', tier: 'fast',
      command: process.execPath, args: ['tools/build_runtime_bundle.cjs', '--check'], timeoutMs: 60000,
    },
    {
      id: 'SYN-BUNDLE-01', area: '공통/문법', title: '생성 runtime bundle 문법 검사', tier: 'fast',
      command: process.execPath, args: ['--check', 'dist/app-runtime.bundle.js'], timeoutMs: 60000,
    },
    {
      id: 'SYN-PY-01', area: '공통/문법', title: '백엔드 핵심 모듈 컴파일 검사', tier: 'fast',
      command: pythonExe, args: ['-m', 'py_compile', ...BACKEND_SOURCES], timeoutMs: 120000,
      clearEnv: ['SSL_CERT_FILE'],
    },
    nodeFile('UNIT-ARCH-01', '공통/구조', '실행 기준·identity·revision 구조 계약', 'tests/frontend/architecture_source_contracts.test.cjs', 'fast'),
    nodeFile('ARCH-TARGETS-01', '공통/구조', '20개 메뉴·탭 소유권과 저장·잠금 목표 계약', 'tests/frontend/menu_modularization_target.test.cjs', 'fast'),
    nodeFile('ARCH-IMPORTS-01', '공통/구조', 'ESM import graph·전역·mutable export 계약', 'tests/frontend/import_graph_contracts.test.cjs', 'fast'),
    nodeFile('ARCH-ENFORCE-01', '공통/구조', 'manifest·module size·저장 경계·bundle 통합 계약', 'tests/frontend/task8_architecture_gates.test.cjs', 'fast'),
    nodeFile('UI-CJK-01', '공통/화면', '작은 창 한글 단어·조립공장 탭 라벨 가시성 계약', 'tests/frontend/task8_responsive_cjk.test.cjs', 'fast'),
    nodeFile('RUNTIME-BUILD-01', '공통/실행 기준', '구버전 탭 클릭 차단·새 빌드 적용 게이트', 'tests/frontend/runtime_build_stale_guard.test.cjs', 'fast'),
    nodeFile('RUNTIME-BUILD-03', '공통/실행 기준', 'ESM 런타임 모듈 변경의 build ID·캐시 무효화', 'tests/frontend/runtime_bundle_build_id.test.cjs', 'fast'),
    nodeFile('ANALYSIS-LLM-01', 'AI 분석 연동', '모델 설정 저장·경쟁사 분석 LLM 선택 계약', 'tests/frontend/competitor_analysis_model_selection.test.cjs', 'fast'),
    nodeFile('DETAIL-05', '6 상세페이지', '일괄 생성 실행 예정 기준·방식 가시성', 'tests/frontend/section_batch_execution_preview.test.cjs', 'fast'),
    nodeFile('DETAIL-06', '6 상세페이지', '섹션 2장 병렬 실행·로컬 아카이브 이미지 주소', 'tests/frontend/section_batch_parallel_archive_url.test.cjs', 'fast'),
    nodeFile('DETAIL-07', '6 상세페이지', '지시문 반영 재생성 버튼 이벤트 전파', 'tests/frontend/preview_instruction_regeneration.test.cjs', 'fast'),
    nodeFile('DETAIL-08', '6 상세페이지', 'A/B/C 후보 선택 토큰 갱신·빠른 비교 카드 폭 제한', 'tests/frontend/task7_menu_event_ownership.test.cjs', 'fast'),
    nodeFile('UI-CARD-01', '공통/화면', '미리보기 빠른 비교 카드 긴 메타데이터 넘침 방지', 'tests/frontend/preview_variant_card_layout.test.cjs', 'fast'),
    nodeFile('DETAIL-09', '6 상세페이지', 'A/B 선택 즉시 반영·최근 생성컷 작업본 저장·복원', 'tests/frontend/a_b_cut_persistence_regression.test.cjs', 'fast'),
    nodeFile('DETAIL-10', '6 상세페이지', '미생성 색상옵션 섹션 이동·옵션 결과 이미지 선택', 'tests/frontend/preview_missing_section_image_selection.test.cjs', 'fast'),
    nodeFile('DETAIL-11', '6 상세페이지', '15개 개별 생성·프롬프트 버전·현재 경쟁사 scope 계약', 'tests/frontend/competitor_section_plan_prompt_contract.test.cjs', 'fast'),
    nodeFile('FACTORY-PUBLISH-01', '7 전송', '최종등록 준비 카드와 scoped 상세페이지 게이트 일치', 'tests/frontend/task7_factory_publish_tab.test.cjs', 'fast'),
    nodeFile('CAFE24-OPTION-SYNC-01', '7 전송', '상세 HTML 이미지 전송·옵션별 재고 직접 저장 경계', 'tests/frontend/cafe24_option_sorter_bridge.test.cjs', 'fast'),
    nodeFile('CAFE24-DETAIL-IMAGE-01', '7 전송', 'Cafe24 상세 이미지 404 메타데이터 원본 fallback', 'tests/frontend/cafe24_detail_image_hydration.test.cjs', 'fast'),
    nodeFile('SYN-SYNC-WARN-01', '공통/저장', '신화사 자산관 동일 오류 중복 로그 억제·성공 후 재기록', 'tests/frontend/work_bundle_sync_warning_dedupe.test.cjs', 'fast'),
    nodeFile('CMD-UI-02', '공통/명령', '옵션 분류기 진입 저장 메타데이터 소유 경계', 'tests/frontend/task7_factory_store_authority.test.cjs', 'fast'),
    nodeFile('DB-09', '1 제품/DB', '후보 선택 단일 클릭 소유권·현재 작업 렌더 정합성', 'tests/frontend/factory_candidate_click_invariant.test.cjs', 'fast'),
    nodeFile('DB-10', '1 제품/DB', '격리 Chrome 신뢰 포인터 후보 선택·상품 경계·좁은 화면 카드 가시성', 'tools/verify_factory_candidate_pointer_selection_v159.cjs'),
    nodeFile('DB-13', '4 경쟁사', '격리 Chrome 후보 실제 선택·반복 해제·PSD 탭 브랜치 격리·VM 상세수집 활성화', 'tools/verify_factory_competitor_candidate_pointer_v588.cjs'),
    nodeFile('DB-11', '1 제품/DB', '신화사DB API Hub 전용 후보·상세 요청은 PDP 인증 상태와 분리', 'tests/frontend/sinhwa_api_hub_only_contract.test.cjs', 'fast'),
    nodeFile('DB-12', '1 제품/DB', '후보 수집 임시 복제본의 중복 DB 탭 렌더 방지', 'tests/frontend/factory_db_render_coalescing.test.cjs', 'fast'),
    {
      id: 'ARCH-LIFECYCLE-01', area: '공통/구조', title: '메뉴·탭 listener와 disposer 독립 수명주기', tier: 'fast',
      command: process.execPath,
      args: [
        '--test',
        'tests/frontend/menu_contracts.test.cjs',
        'tests/frontend/task5_low_coupling_menus.test.cjs',
        'tests/frontend/task6_domain_route_modules.test.cjs',
        'tests/frontend/task7_menu_event_ownership.test.cjs',
        'tests/frontend/task7_factory_modules.test.cjs',
        'tests/frontend/task7_shell_modules_unit.test.cjs',
      ],
      timeoutMs: 180000,
    },
    {
      id: 'SAVE-MIGRATION-01', area: '공통/저장', title: 'legacy·IDB·server·archive·workfile migration 계약', tier: 'fast',
      command: process.execPath,
      args: [
        '--test',
        'tests/frontend/persistence_migration_contracts.test.cjs',
        'tests/frontend/persistence_gateway_contracts.test.cjs',
        'tests/frontend/persistence_destination_cas.test.cjs',
      ],
      timeoutMs: 180000,
    },
    {
      id: 'SAVE-CONCURRENCY-01', area: '공통/동시 편집', title: '두 세션 stale writer·takeover·completion race 계약', tier: 'fast',
      command: process.execPath,
      args: [
        '--test',
        'tests/frontend/workspace_lock_contracts.test.cjs',
        'tests/frontend/workspace_fencing_orchestrator.test.cjs',
        'tests/frontend/workspace_midflight_fencing.test.cjs',
        'tests/frontend/task7_workspace_lock_completion_races.test.cjs',
        'tests/frontend/task7_workspace_lock_takeover_guards.test.cjs',
        'tests/frontend/task7_workspace_lock_takeover_races.test.cjs',
        'tests/frontend/task7_workspace_lock_transition_races.test.cjs',
        'tests/frontend/task7_takeover_hydration_authority.test.cjs',
      ],
      timeoutMs: 180000,
    },
    nodeFile('SAVE-CONCURRENCY-02', '공통/동시 편집', '비동기 초안의 최신 사용자 상태 병합 계약', 'tests/frontend/factory_store_async_rebase.test.cjs', 'fast'),
    ...MODULE_TARGET_GATES.map(({ id, title }) => nodeTestPattern(
      id,
      '공통/모듈 경계',
      `${title} 전용 구현·registry gate`,
      'tests/frontend/menu_modularization_target.test.cjs',
      `^${id}:`,
    )),
    {
      ...nodeFile('UNIT-FE-01', '공통/데이터 격리', '프론트 실제 함수 단위 계약', 'tests/frontend/factory_core_contracts.test.cjs', 'fast'),
      browser: true,
    },
    {
      ...nodeTestPattern(
        'SAVE-22',
        '7 저장/내보내기',
        '새 작업 전 실제 저장 버튼의 작업본·파일 저장 및 전환 계약',
        'tests/frontend/factory_core_contracts.test.cjs',
        '^새 작업의 저장 선택은 현재 작업을 보존한 뒤 전환을 계속한다$',
      ),
      browser: true,
    },
    nodeFile('RESTORE-UI-01', '공통/작업파일', '완성 작업 복원·이미지 백업·상태 정합성 계약', 'tests/frontend/task8_restore_lifecycle_behavior.test.cjs', 'fast'),
    nodeFile('SAVE-IDENTITY-01', '공통/데이터 격리', '작업파일·제품명·기본이미지 불변 identity 및 혼합 복원 거부', 'tests/frontend/workspace_work_identity_contract.test.cjs', 'fast'),
    nodeFile('SAVE-IDENTITY-02', '공통/데이터 격리', '시작 복원·저장·새 작업·상시 identity 카드 런타임 경계', 'tests/frontend/workspace_work_identity_runtime_contract.test.cjs', 'fast'),
    nodeFile('MENU-NAV-01', '공통/메뉴', '12개 메뉴·7개 탭 라우팅과 실제 버튼 handoff 계약', 'tests/frontend/menu_navigation_characterization.test.cjs', 'fast'),
    nodeTestPattern(
      'ANALYSIS-SYNC-01',
      'AI 분석/조립공장 연동',
      '조립공장 최신값의 카테고리 표시·규격 단위 보존',
      'tests/frontend/task7_factory_cafe24_writer_retirement.test.cjs',
      'analysis-hub factory import preserves',
    ),
    nodeTestPattern(
      'CAFE24-CREATE-TARGET-01',
      '7 저장/내보내기',
      '신규 상품 생성 직후 기존 상품 수정 대상으로 승격',
      'tests/frontend/task7_factory_cafe24_writer_retirement.test.cjs',
      'successful Cafe24 create immediately',
    ),
    nodeFile('UNIT-FE-02', '공통/실행 안정성', '브라우저 인프라 실패만 1회 재시도', 'tests/frontend/regression_runner_contracts.test.cjs', 'fast'),
    {
      id: 'UNIT-AUTH-01', area: '공통/동시 편집', title: 'lease·fence·작업파일·명령 차단 단위 계약', tier: 'fast',
      command: process.execPath,
      args: [
        '--test',
        'tests/frontend/workspace_lock_contracts.test.cjs',
        'tests/frontend/workspace_fencing_orchestrator.test.cjs',
        'tests/frontend/workfile_stale_guard.test.cjs',
        'tests/frontend/command_authority_guard.test.cjs',
      ],
      timeoutMs: 120000,
    },
    {
      id: 'UNIT-BE-01', area: '공통/로컬 아카이브', title: '백엔드 pytest 단위 계약', tier: 'fast',
      command: pythonExe, args: ['-m', 'pytest', '-q', 'backend/tests'], timeoutMs: 180000,
      clearEnv: ['SSL_CERT_FILE'],
    },
    nodeFile('UI-BASE-01', '공통/화면', '앱 로드·이미지 깨짐·기본 렌더', 'tools/verify_factory_integrity_cdp_v80.cjs'),
    nodeFile('UI-RESP-01', '공통/화면', '작은 창 사이즈 확인 버튼·상태 레일 도달성', 'tools/verify_factory_responsive_controls_v230.cjs'),
    nodeFile('SCOPE-01', '1 제품/DB', '현재 상품 식별자 드리프트 차단', 'tools/verify_factory_identity_drift_cdp_v88.cjs'),
    nodeFile('SCOPE-02', '1 제품/DB', '다른 작업파일 데이터 격리', 'tools/verify_factory_workspace_isolation_cdp_v83.cjs'),
    nodeFile('SCOPE-OAUTH-01', '공통/저장', 'Cafe24 OAuth 상태 갱신과 작업파일 revision 분리', 'tools/verify_oauth_status_workspace_isolation_v246.cjs'),
    nodeFile('SCOPE-REV-01', '공통/저장', '세 세션 독립 브랜치 revision·이전 저장 거부', 'tools/verify_three_session_workspace_revision_v230.cjs'),
    nodeFile('AUTH-01', '공통/동시 편집', '두 창 편집권 인계·stale 저장 차단·작은 창 복구 UI', 'tools/verify_workspace_conflict_cdp_v233.cjs'),
    nodeFile('DB-01', '1 제품/DB', '새 상품 후보 범위와 후보 없음 처리', 'tools/verify_factory_candidate_new_draft_scope_v163.cjs'),
    nodeFile('DB-02', '1 제품/DB', 'DB/Cafe24 확정 선택 새로고침 유지', 'tools/verify_factory_candidate_confirmation_reload_cdp_v185.cjs'),
    nodeFile('DB-03', '1 제품/DB', '초안 첫 저장·작업파일 저장 뒤 후보 선택 유지', 'tools/verify_factory_candidate_workspace_transition_v220.cjs'),
    nodeFile('DB-04', '1 제품/DB', '기존 저장본 draft 후보 복구와 다른 작업 후보 차단', 'tools/verify_factory_candidate_restore_recovery_v221.cjs'),
    nodeFile('DB-05', '1 제품/DB', '브라우저 시작 복원 draft 후보 복구와 다른 작업 후보 차단', 'tools/verify_factory_candidate_startup_restore_v223.cjs'),
    nodeFile('DB-06', '1 제품/DB', '서버/자산 복원 draft 후보 복구와 다른 작업 후보 차단', 'tools/verify_factory_candidate_asset_restore_v224.cjs'),
    nodeFile('FIELD-01', '1 제품/DB', '사용용도 확정값 Ctrl+F5 유지', 'tools/verify_factory_usage_ctrl_f5_persistence_v218.cjs'),
    nodeFile('FIELD-02', '3 필수값', '선택한 값만 신화사DB/Cafe24 명시 전송', 'tools/verify_factory_selected_field_transfer_v219.cjs'),
    nodeFile('FIELD-03', '1 시작 입력', '한글 IME 상품명 저장·F5 전체 복원', 'tools/verify_factory_product_name_ime_reload_v373.cjs'),
    nodeFile('IMG-01', '2 대표이미지', '기본 이미지 새로고침 복원', 'tools/verify_factory_input_image_reload_v165.cjs'),
    nodeFile('IMG-03', '1 시작 이미지 교체', '보이는 버튼·대용량 캐시 충돌·새로고침 복원', 'tools/verify_factory_product_image_replacement_cdp_v1.cjs'),
    nodeFile('IMG-02', '2~5 생성 이미지', '생성 이미지 즉시 저장·복원', 'tools/verify_factory_persistence_cdp_v81.cjs'),
    nodeFile('OPT-01', '4 색상옵션', '옵션분류기와 조립공장 색상컷 연동', 'tools/verify_color_option_factory_sync_cdp_v187.cjs'),
    nodeFile('OPT-02', '4 색상옵션', '옵션 3,3,3,3 배열·드래그 교환', 'tools/verify_option_map_layout_drag_cdp_v137.cjs'),
    nodeFile('OPT-03', '4 색상옵션', '옵션 생성 결과 조립공장 전송', 'tools/verify_option_sorter_send_factory_cdp_v189.cjs'),
    nodeFile('OPT-05', '4 색상옵션', '원본 사진 즉시 로컬 보관·F5 자동 복원', 'tools/verify_option_sorter_source_archive_reload_v458.cjs'),
    nodeFile('OPT-06', '4 색상옵션', '생성 결과 보관 PNG 카드·확대보기·다운로드 F5 복원', 'tools/verify_option_sorter_result_archive_reload_v461.cjs'),
    nodeFile('OPT-08', '4 색상옵션', '더블클릭 빠른 배치·무재렌더 드래그·GPT OAuth 번호 색상명', 'tests/frontend/optionsorter_quick_assign_gpt_color.test.cjs', 'fast'),
    nodeFile('DETAIL-01', '6 상세페이지', '고객 화면 작업용 라벨 제거', 'tools/verify_factory_section_labels_cdp_v96.cjs'),
    nodeFile('DETAIL-02', '6 상세페이지', '현재 섹션 완료 후 생성 중단', 'tools/verify_section_graceful_stop_cdp_v208.cjs'),
    nodeFile('DETAIL-03', '6 상세페이지', '개별 섹션 재생성 후보 추가·실패 보존', 'tools/verify_section_regeneration_cdp_v214.cjs'),
    nodeFile('DETAIL-04', '6 상세페이지', '전체 이미지 JPG 원본 비율 보존', 'tools/verify_detail_jpg_full_image_cdp_v215.cjs'),
    nodeFile('PROGRESS-01', '공통/진행상태', '5초 이상 작업 진행 로그·상태 표시', 'tools/verify_factory_progress_observability_cdp_v170.cjs'),
    nodeFile('PERF-00', '공통/성능', '진행률 갱신은 공정/로그 패널을 다시 만들지 않음', 'tools/verify_factory_progress_patch_perf_v217.cjs'),
    nodeFile('PERF-02', '공통/성능', '분석·상세생성 주기 갱신은 전체 화면을 다시 만들지 않음', 'tools/verify_factory_periodic_ticker_patch_cdp_v001.cjs'),
    nodeFile('PERF-03', '공통/성능', 'VM 후보 폴링은 DB 화면을 전체 다시 그리지 않음', 'tools/verify_factory_vm_poll_render_stability_cdp_v002.cjs'),
    nodeFile('GENERATE-01', '2~6 생성 공정', '생성 중·완료·실패 상태 전이', 'tools/verify_factory_generation_status_cdp_v119.cjs'),
    nodeFile('GENERATE-02', '3 필수값/5 생성', '완료 사이즈 결과의 후보 확정 후 보존·확대·선택', 'tools/verify_factory_size_preview_confirm_cdp_v545.cjs'),
    nodeFile('PERF-01', '공통/성능', '96개 후보 렌더·메모리 기준', 'tools/measure_factory_perf_cdp_v79.cjs'),
    nodeFile('SAVE-01', '7 저장/내보내기', '로컬 아카이브 비삭제 보존', 'tools/verify_local_archive_preservation_v123.cjs'),
    nodeFile('SAVE-02', '7 저장/내보내기', '작업파일 저장·열기 전체 상태', 'tools/verify_factory_project_file_cdp_v84.cjs'),
    nodeFile('SAVE-03', '7 저장/내보내기', '새 작업은 빈 상태로 완전 분리', 'tools/verify_factory_new_file_blank_cdp_v85.cjs'),
    nodeFile('SAVE-25', '7 저장/내보내기', '새 작업 포인터 교체·F5·다중 탭 문서 격리', 'tools/verify_new_work_multitab_reload_isolation_v371.cjs'),
    nodeFile('SAVE-04', '7 저장/내보내기', '같은 작업파일 범위 새로고침 복원', 'tools/verify_workfile_scoped_reload_cdp_v138.cjs'),
    nodeFile('SAVE-05', '7 저장/내보내기', 'Ctrl+F5 로컬 아카이브 부트스트랩', 'tools/verify_workfile_ctrl_f5_archive_bootstrap_cdp_v195.cjs'),
    nodeFile('SAVE-33', '7 저장/내보내기', '보관 archive ID 결과의 복원 경고 정확성', 'tests/frontend/session_asset_restore_warning.test.cjs', 'fast'),
    nodeFile('SAVE-38', '7 저장/내보내기', '최근 저장 작업 자동 보관 연결·새 작업 초기화 경계', 'tests/frontend/workfile_archive_autorefresh.test.cjs', 'fast'),
    nodeFile('SAVE-39', '7 저장/내보내기', '부분 렌더 뒤 보관함 복원·새로고침·불러오기 버튼 재연결', 'tests/frontend/local_archive_event_delegation.test.cjs', 'fast'),
    nodeFile('SAVE-40', '7 저장/내보내기', '같은 원본 legacy archive marker가 실제 복원을 막지 않음', 'tests/frontend/factory_archive_identity_recovery.test.cjs', 'fast'),
    nodeFile('SAVE-41', '7 저장/내보내기', 'Ctrl+F5 뒤 session revision 충돌의 첫 필수값 저장 재기준화', 'tests/frontend/session_same_revision_recovery_reconciliation.test.cjs', 'fast'),
    nodeFile('SAVE-42', '7 저장/내보내기', '필수값 확정의 즉시 canonical session 저장', 'tests/frontend/force_save_immediate_persistence.test.cjs', 'fast'),
    nodeFile('SAVE-06', '7 저장/내보내기', 'Cafe24 등록 성공·실패 뒤 현재 작업 보존', 'tools/verify_factory_final_registration_preserves_work_v225.cjs'),
    nodeFile('VM-01', '4 경쟁사', 'VM 브리지 요청·결과 계약', 'tools/verify_vm_candidate_bridge_contract.cjs'),
    nodeFile('VM-02', '4 경쟁사', 'VM 후보 현재 작업 범위 격리', 'tools/verify_factory_vm_scope_isolation_v130.cjs'),
    nodeFile('VM-03', '4 경쟁사', '빈 소스 캐시 뒤 현재 VM 후보 카드 표시', 'tests/frontend/task7_factory_competitor_tab.test.cjs', 'fast'),
    nodeFile('VM-08', '4 경쟁사', '다른 작업 후보 재라벨링·무관 상품 격리·힌트 검색 순서', 'tests/frontend/comp_market_finalize_results.test.cjs', 'fast'),
    nodeFile('CMD-UI-01', '4 경쟁사', '패널 토글 단일 명령 저장 경계', 'tests/frontend/factory_candidate_apply_command_policy.test.cjs', 'fast'),
    nodeFile('MARKET-01', '4 경쟁사', '선택 후보만 상세수집 범위 유지', 'tools/test_comp_market_selection_scope_v180.cjs'),
    nodeFile('FULL-01', '1 제품/DB', '필수값 확인 상태 새로고침 유지', 'tools/verify_factory_field_confirmation_persistence_cdp_v143.cjs', 'full'),
    nodeFile('FULL-02', '공통/공정 이동', '공정 탭 이동 상태 보존', 'tools/verify_factory_stage_jump_cdp_v171.cjs', 'full'),
    nodeFile('FULL-03', '4 경쟁사', '마켓별 후보 누적', 'tools/test_comp_market_accumulation_v179.cjs', 'full'),
    nodeFile('FULL-04', '4 경쟁사', '마켓 상태 정합성', 'tools/test_comp_market_status_reconciliation_v183.cjs', 'full'),
    nodeFile('FULL-05', '4 경쟁사', '마켓 상태 UI 정합성', 'tools/verify_comp_market_status_reconciliation_cdp_v183.cjs', 'full'),
    nodeFile('FULL-06', '7 저장/내보내기', '작업파일 불러오기 성능', 'tools/measure_workfile_import_perf_cdp_v122.cjs', 'full'),
    nodeFile('FULL-07', '4 색상옵션', '옵션 이미지 추가 UI', 'tools/verify_option_sorter_add_image_cdp_v126.cjs', 'full'),
    nodeFile('FULL-08', '4 색상옵션', '옵션분류기 전체 작업 흐름', 'tools/verify_option_sorter_workflow_cdp_v127.cjs', 'full'),
    nodeFile('FULL-09', '1 제품/DB', 'Cafe24 후보 제품 링크 표시', 'tools/verify_factory_cafe24_product_link_screen_v165.cjs', 'full'),
    nodeFile('FULL-10', '6 상세페이지', '15섹션 진행률 정합성', 'tools/verify_factory_detail_progress_cdp_v184.cjs', 'full'),
    nodeFile('FULL-11', '7 저장/내보내기', '최근 작업파일 4개 표시', 'tools/verify_factory_recent_workfile_row_cdp_v147.cjs', 'full'),
    nodeFile('FULL-12', '4 경쟁사', '로그인 수동개입 요청 UX', 'tools/verify_vm_manual_intervention_cdp_v181.cjs', 'full'),
  ];
}

module.exports = {
  FRONTEND_SOURCES,
  MANUAL_EXTERNAL_GATES,
  MODULE_TARGET_GATES,
  RUNTIME_SOURCES,
  buildRegressionSteps,
};
